version: '3'

services:
  postgres:
    image: postgres:15.3
    container_name: saria-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - saria-postgres:/data/postgres
    ports:
      - '5431:5432'

volumes:
  saria-postgres:
